### ISSUE TITLE
Doesn't work on Godot 4.0.2

### ISSUE THREAD

**Issue by Arthur-Melnik** [finepointcgi/Godot-Open-AI-GPT-Integration#2]
Looks like script can't parse key, I entered it in gui, but there are errors on request
```
SCRIPT ERROR: Invalid get index 'choices' (on base: 'Dictionary').
          at: _on_request_completed (res://addons/GPTIntegration/GPTIntegration.gd:160)
{ "error": { "message": "You didn\'t provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you\'re accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.", "type": "invalid_request_error", "param": <null>, "code": <null> } }
```

**Comment by finepointcgi** [comment]
Fixed in latest push.
Thank you for the ticket!

**Comment by kennethrapp** [comment]
It isn't fixed, I'm currently getting this same error. Printing out the headers array inside call_GPT shows it doesn't append the api key to the Authorization header. I was able to fix this by moving the headers array into call_GPT:

`func call_GPT(prompt):
	
	var headers = ["Content-Type: application/json","Authorization: Bearer " + api_key]
	var body = JSON.new().stringify({
		"prompt": prompt,
		"temperature": temperature,
		"max_tokens": max_tokens,
		"model": "text-davinci-003"
	})
(...)
`

**Comment by finepointcgi** [comment]
> It isn't fixed, I'm currently getting this same error. Printing out the headers array inside call_GPT shows it doesn't append the api key to the Authorization header. I was able to fix this by moving the headers array into call_GPT:
> 
> `func call_GPT(prompt):
> 
> ```
> var headers = ["Content-Type: application/json","Authorization: Bearer " + api_key]
> var body = JSON.new().stringify({
> 	"prompt": prompt,
> 	"temperature": temperature,
> 	"max_tokens": max_tokens,
> 	"model": "text-davinci-003"
> })
> ```
> 
> (...) `

This is what i have in the current release:
![image](https://user-images.githubusercontent.com/12012300/232246521-e5aeb1f1-2db2-469e-8647-35c0f8ecab2e.png)
it "should" be fixed

**Comment by kennethrapp** [comment]
Ok. For some reason the version in Godot's AssetLib isn't up to date. I'll just clone it directly then, nvm.

**Comment by finepointcgi** [comment]
I may need to ask them to update it
