### ISSUE TITLE
some errs with Godot4.0.2

### ISSUE THREAD

**Issue by jinruozai** [finepointcgi/Godot-Open-AI-GPT-Integration#3]
os:mac13.3.1
godot:4.0.2

res://addons/GPTIntegration/GPTIntegration.gd:225 - Attempt to call function 'get_as_text' in base 'null instance' on a null instance.
res://addons/GPTIntegration/GPTIntegration.gd:161 - Invalid get index 'choices' (on base: 'Nil').

**Comment by clemens-tolboom** [comment]
Did you ran into more errors? PR #4 fixes one of yours.

**Comment by finepointcgi** [comment]
This should be fixed with pr #4
