### ISSUE TITLE
invalid_api_key: when editing API key using Godot editor is overridden on save

### ISSUE THREAD

**Issue by clemens-tolboom** [finepointcgi/Godot-Open-AI-GPT-Integration#6]
When I edit the API key in `addons/GPTIntegration/settings.json` using Godot text edit and save it this new value is not used **and** overridden when closing Godot.

## Workaround

- disable plugin
- edit `addons/GPTIntegration/settings.json`
- enable plugin

**Comment by finepointcgi** [comment]
I have just fixed this
Thanks!
