### ISSUE TITLE
Doesn't work on Godot 4.0.3

### ISSUE THREAD

**Issue by Virjoinga** [finepointcgi/Godot-Open-AI-GPT-Integration#8]
The steps say to clone it to my project folder, which I have (the root of it), and it doesn't show as a plugin in Godot but the folder shows in the filesystem. Maybe the steps are written poorly?

**Comment by clemens-tolboom** [comment]
Addons belong into the addons directory.

How is your tree?

**Comment by MarqCl** [comment]
me pasó lo mismo, debes descargarlo desde godot en la pestaña assets, para buscarlo rápido escribe GPT y luego das clic en el nombre y le das a instalar. luego en configuraciones de projecto buscas la parte donde dice PLUGINS y le das a activar. (spanish)

I had the same issue. You must download it from Godot in the 'Assets' tab. To find it quickly, type 'GPT' and then click on the name and hit 'Install.' After that, go to 'Project Settings,' look for the section that says 'PLUGINS,' and click 'Activate.' (English)

**Comment by Virjoinga** [comment]
> Addons belong into the addons directory.
> 
> How is your tree?

Sorry for the very late response, I had it in the wrong folder.
