### ISSUE TITLE
Godot 4.1.1 Unable to load script from path...GPTIntergration.gd

### ISSUE THREAD

**Issue by yrthilian** [finepointcgi/Godot-Open-AI-GPT-Integration#9]
Godot 4.1.1 Unable to load script from path...GPTIntergration.gd This might be due to a code error in that script

First time trying to add this to my project can not get past this error
![image](https://github.com/finepointcgi/Godot-Open-AI-GPT-Integration/assets/1047072/9cba4131-1078-4f72-9771-420727854663)

**Comment by finepointcgi** [comment]
Im currently running that version and it works fine for me. Where did you pull it down the asset site or the github?

**Comment by wuwenthink** [comment]
> Im currently running that version and it works fine for me. Where did you pull it down the asset site or the github?我目前正在运行这个版本，它对我来说工作得很好。你是从哪里下载的资产网站还是github？

I just downloaded version 4.1 of the website
Then use git to clone this tool, and then click enable in the plug-in, it will report an error, the same as the owner of the error content

**Comment by wuwenthink** [comment]
> Im currently running that version and it works fine for me. Where did you pull it down the asset site or the github?

I know the problem, a very basic folder nesting error

There is also an addons folder in the folder after decompression, which will cause an error. You need to manually drag the folder in the addons folder to the root directory of addons.

**Comment by WillSams** [comment]
Thanks, that fixed the issue for me. I extracted the contents to an `addons` folder in the root of my project.  I moved the **GPTIntegration** folder to my root assets folder and was able to enable the plugin afterwards.

**Comment by wuwenthink** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我可能无法马上回复您的邮件。但会尽快给您回复。

**Comment by wuwenthink** [comment]
> Thanks, that fixed the issue for me. I extracted the contents to an `addons` folder in the root of my project. I moved the **GPTIntegration** folder to my root assets folder and was able to enable the plugin afterwards.

perfect
